### ISSUE TITLE
Incorrect port in deploy-for-production.sh, formatting issues in README.md

### ISSUE THREAD

**Issue by benjaminlimjt** [jenkins-docs/building-a-multibranch-pipeline-project#121]
In `jenkins/scripts/deploy-for-production.sh`,  Line 32, the script is serving the application at the wrong port. In the tutorial [Build a Multibranch Pipeline Project](https://www.jenkins.io/doc/tutorials/build-a-multibranch-pipeline-project/), it is stated that the web application is available at `http://localhost:5000`. However, the script serves the application at port 3000.

Proposed change:

**Before**
```
./node_modules/serve/build/main.js -s build -l 3000 &
```

**After**
```
./node_modules/serve/build/main.js -s build -l 5000 &
```

In addition, there is a hyperlink formatting issue in `README.md`, Line 21. (unless it is intentional.)

Not making a pull-request as it seems to not be accepted in this repository.

**Comment by MarkEWaite** [comment]
Thanks for the report.  Fixed in 

* #184
