### ISSUE TITLE
sh: react-scripts: command not found

### ISSUE THREAD

**Issue by miladini** [jenkins-docs/building-a-multibranch-pipeline-project#39]
I get the following error, and its propagation, when following the instructions:
sh: react-scripts: command not found

**Comment by miladini** [comment]
This pull request solved it for me. Enjoy!
https://github.com/jenkins-docs/building-a-multibranch-pipeline-project/pull/38

**Comment by hwlee96** [comment]
Did you get the error when you were running development stage, but you weren't able to access the react app at localhost:3000 ?

**Comment by MarkEWaite** [comment]
Resolved in most recent changes to the tutorial
